on:
  release:
    types: [published]

jobs:
  check-tag:
    name: Check tag
    runs-on: ubuntu-24.04
    steps:
      - run: echo "${{ github.ref }}"
      - name: Check tag
        run: "[[ '${{ github.ref }}' =~ ^refs/tags/v[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}(-[0-9A-Za-z\\.-]+)?(\\+[0-9A-Za-z\\.-]+)?$ ]]"
      - if: ${{ failure() }}
        run: echo "::error ::moiccu"
