on:
  release:
    types: [published]

jobs:
  check-tag:
    name: Check tag
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: echo "${{ github.ref }}"
      # - name: Check tag
      #   run: "[[ '${{ github.ref }}' =~ ^refs/tags/v[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}(-[0-9A-Za-z\\.-]+)?(\\+[0-9A-Za-z\\.-]+)?$ ]] && exit 0 || exit 1"
      - uses: actions/github-script@v7
        with:
          script: |
            const semver = require('./.github/workflows/scripts/semver.js')
            return semver({ context })
